### ISSUE TITLE
Music Not Working

### ISSUE THREAD

**Issue by LotusRiver** [ZaneYork/SMAPI-Android-Installer#146] opened 2021-08-21 15:57 UTC
Music still isn't working. Im on Galaxy Note 20 Ultra. Works fine outside of SMAPI, I have 0 mods installed and it still doesn't work with this version of SMAPI. I love the music so it's mildly disappointing. No hate to the dev, you're doing a great job!

**Comment by lividhen** [comment] 2021-08-21 17:40
Duplicate of [#54](https://github.com/ZaneYork/SMAPI-Android-Installer/issues/54#issuecomment-864800295)

**Comment by ZaneYork** [comment] 2021-09-28 03:25
Duplicate of #54

**Closed by ZaneYork** 2021-09-28 03:25 UTC
