### ISSUE TITLE
SMAPI Installer Freezing

### ISSUE THREAD

**Issue by applesauce2020** [ZaneYork/SMAPI-Android-Installer#177] opened 2022-03-16 23:17 UTC
I have tried to install latest SMAPI but it keeps freezing at 49% Signing. I cannot install older versions of SMAPI without getting errors that the file may be corrupt.

**Comment by ZaneYork** [comment] 2022-04-07 09:33
Duplicate of #178 
Needs more details

**Closed by ZaneYork** 2022-04-07 09:33 UTC
