### ISSUE TITLE
The latest installer installs wrong version

### ISSUE THREAD

**Issue by 60iTomi** [ZaneYork/SMAPI-Android-Installer#124] opened 2021-03-12 11:55 UTC
So, when I installed v_3.7.6.1, everything went fine. But when I open SMAPI, the homescreen says v_3.7.6.1., Plus when I start the modded version, it just crashes. Any idea how to fix it? I'm pretty sure that the problem is at me.

**Comment by ZaneYork** [comment] 2022-04-08 01:59
Duplicate of #175

**Closed by ZaneYork** 2022-04-08 01:59 UTC
