### ISSUE TITLE
It's a problem with versions before Android 6

### ISSUE THREAD

**Issue by wally232** [ZaneYork/SMAPI-Android-Installer#11] opened 2020-05-04 05:48 UTC
The problem is related to Android 6 or earlier.

Until SMAPI Installer 1.4.4 version
The xnb file in CustomLocalization mode has been applied.

SMAPI Installer 1.4.5 version later.
The xnb file in CustomLocalization mode is not applied.

Prior to Android 6.
Is there a way to apply the xnb file?

**Comment by ZaneYork** [comment] 2020-05-04 06:15
Custom Localization is&nbsp; depends on&nbsp; MonoMod, it can't works on&nbsp; device before Android 6, which monomod has&nbsp; disabled



---Original---

**Comment by ZaneYork** [comment] 2022-04-07 09:21
Enable Harmony option in settings of installer may help

**Comment by ZaneYork** [comment] 2022-04-07 09:22
Duplicate of #49

**Closed by ZaneYork** 2022-04-07 09:21 UTC
