### ISSUE TITLE
Android 12 No Music

### ISSUE THREAD

**Issue by NamiDabi** [ZaneYork/SMAPI-Android-Installer#180] opened 2022-03-31 11:16 UTC
Hi, so ive tried basically everything. Reinstalling, changing content patcher, going new save and clean slate, getting a lower version SMAPI, copying the obb and even downloading it from somewhere else then placing into com.zane.stardewvalley.

Both SMAPI and SDV are latest versions, mods are working fine. The normal SDV has music, SMAPI version does not with or without mods. Ive resorted to using spotify for the background music for the meantime 😢

**Comment by ChulkyBow** [comment] 2022-03-31 14:56
Android 11... same

**Comment by ZaneYork** [comment] 2022-04-05 13:05
Try latest 3.7.6.10

**Comment by ZaneYork** [comment] 2022-04-07 09:23
Duplicate of #54

**Closed by ZaneYork** 2022-04-07 09:23 UTC

**Comment by NamiDabi** [comment] 2022-04-07 16:26
omg that fixed it. Thank you!!
