### ISSUE TITLE
When will this mod port be updated?

### ISSUE THREAD

**Issue by dmnck2017** [ZaneYork/SMAPI-Android-Installer#76] opened 2021-01-19 20:47 UTC
Just curious when it will be updated? If I need to wait until the big update for SDV for android then i will but if its updated before that I'll do that.

**Comment by AndroidPLZ** [comment] 2021-01-21 08:40
No one knows

**Comment by ZaneYork** [comment] 2022-04-08 02:14
Duplicate of #141

**Closed by ZaneYork** 2022-04-08 02:14 UTC
