### ISSUE TITLE
not working in version 1.4.5.145

### ISSUE THREAD

**Issue by TheDarkness2004** [ZaneYork/SMAPI-Android-Installer#23] opened 2020-07-02 05:37 UTC
I installed and uninstalled it several times and it always keeps the screen black and doesn't work. I'm on the latest version of Stardew Valley and Smapi and on Android 10, I don't know if it's because of my Android

**Comment by 1jezs0** [comment] 2020-08-03 10:30
I think this version of smapi doesnt support android 10

**Comment by ZaneYork** [comment] 2020-09-30 02:31
Needs more details for the issue such as error logs or logcat report to locate the problem

**Comment by ZaneYork** [comment] 2022-04-08 02:17
Duplicate of #175

**Closed by ZaneYork** 2022-04-08 02:17 UTC
