### ISSUE TITLE
What should i do with this?

### ISSUE THREAD

**Issue by TSKERRER** [ZaneYork/SMAPI-Android-Installer#158] opened 2021-12-16 10:59 UTC
![Screenshot_2021-12-16-12-55-47-1935579262](https://user-images.githubusercontent.com/96237754/146359611-a190da66-1d49-4f94-9062-45c9dc207398.png)
 Pls
 help with it

**Comment by lividhen** [comment] 2021-12-22 17:38
Download older versions of the mods from the old files section on nexus mods.
https://web.archive.org/web/20201205160709/https://smapi.io/mods/
This is a capture from December 2020 when 3.7 was the latest version. It may help in finding compatible mods, but a lot of them just say "Latest Version" which isn't very helpful... If it does say "Latest Version" try going to the mod's page on the web archive and look at early december to see if anyone took a capture of it then.

**Comment by ZaneYork** [comment] 2022-04-08 01:40
Duplicate of #141

**Closed by ZaneYork** 2022-04-08 01:40 UTC
