### ISSUE TITLE
crash upon launch

### ISSUE THREAD

**Issue by cityracers** [ZaneYork/SMAPI-Android-Installer#118] opened 2021-02-21 22:37 UTC
I just launched for the first time and I got this message:
![crash](https://user-images.githubusercontent.com/79425020/108641079-36c5b900-7452-11eb-9cde-fd4dfc3cf8bb.png)

**Comment by ZaneYork** [comment] 2022-04-07 09:14
Duplicate of #49 
Disable Harmony in settings of Installer may help

**Closed by ZaneYork** 2022-04-07 09:14 UTC
