### ISSUE TITLE
Smapi android update the latest

### ISSUE THREAD

**Issue by leeeeeeeeenaaaaaa** [ZaneYork/SMAPI-Android-Installer#72] opened 2021-01-04 09:58 UTC
Does smapi work for the playstore android version

**Comment by AndroidPLZ** [comment] 2021-01-05 18:45
Wdym dude it didn't even update to 1.4.8 and the mobile version didn't even get 1.5 yet wtf are you talking about

**Comment by AndroidPLZ** [comment] 2021-01-06 09:40
Also stop editing your comment to make it look like you're right

**Comment by Jazimundo** [comment] 2021-01-06 19:01
I edited it to ask a new question if ur not going to answer it what is the point being so negative???? Like shit calm down

**Comment by lividhen** [comment] 2021-01-06 20:20
> 
> 
> I edited it to ask a new question if ur not going to answer it what is the point being so negative???? Like shit calm down

Generally you would open a new issue, but this works 😂. It normally would, but does not currently, as smapi (for android) is outdated. It will hopefully be updated soon. The PC one is almost always up to date, but the android one is a bit harder to maintain, I think.

**Comment by LuxiMalikSuzumori** [comment] 2021-01-10 23:02
Honestly dont expect it to update for android any time soon. its been needing an update since October

**Comment by LuxiMalikSuzumori** [comment] 2021-01-10 23:03
ive been waiting too ;w;

**Comment by AndroidPLZ** [comment] 2021-01-13 15:17
My guess is that they are waiting for 1.5 since it's coming soon

**Comment by AndroidPLZ** [comment] 2021-01-21 08:41
> Honestly dont expect it to update for android any time soon. its been needing an update since October

Bruh wdym

**Comment by ZaneYork** [comment] 2022-04-08 01:40
Duplicate of #141

**Closed by ZaneYork** 2022-04-08 01:40 UTC
