### ISSUE TITLE
SMAPI Crashes on Launch

### ISSUE THREAD

**Issue by ghost** [ZaneYork/SMAPI-Android-Installer#81] opened 2021-01-29 04:52 UTC
Installed the installer (3.7.6.4) and successfully installed SMAPI. Upon attempting to launch SMAPI it instantly crashes. Trying again yields a brief showing of the app starting screen (With the Companys' Logos), then crashes.

**Comment by Tougal** [comment] 2021-02-02 15:13
Yes!  I have this same exact problem. When I try to launch,  it eventually results in a "Smapi stardew valley failed to start several times. Restore it by clearing history?"

**Comment by ZaneYork** [comment] 2022-04-08 02:02
Duplicate of #175

**Closed by ZaneYork** 2022-04-08 02:02 UTC
