### ISSUE TITLE
What Version of SVE I can use, from the latest SMAPI

### ISSUE THREAD

**Issue by MarchVin** [ZaneYork/SMAPI-Android-Installer#132] opened 2021-04-08 06:46 UTC

**Comment by firereverie** [comment] 2021-04-12 17:35
Flashshifter only hosts the current desktop version on the nexus, they do however host older versions on moddrop. The one you want to look for is 1.11.6.

**Comment by ZaneYork** [comment] 2022-04-08 01:42
Duplicate of #141

**Closed by ZaneYork** 2022-04-08 01:42 UTC
