### ISSUE TITLE
Can't install Smapi Stardew Valley

### ISSUE THREAD

**Issue by MrXarl** [ZaneYork/SMAPI-Android-Installer#128] opened 2021-03-17 21:12 UTC
Hello, I've been trying to fix this error for half a year, but nothing. No, I can install Smapi, but Smapi cannot install Smapi Stardew Valley. I am using version 1.4.5.148

**Comment by ialil** [comment] 2021-05-06 09:41
Same problem mine said failed to sign the game please contact the developer for help

**Comment by Melo426** [comment] 2021-07-28 03:32
same here

**Comment by Melo426** [comment] 2021-07-28 03:33
someone discovered how to fix this?

**Comment by ZaneYork** [comment] 2022-04-08 01:53
Duplicate of #178

**Closed by ZaneYork** 2022-04-08 01:53 UTC
