### ISSUE TITLE
It crashes

### ISSUE THREAD

**Issue by kingkane23** [ZaneYork/SMAPI-Android-Installer#90] opened 2021-01-31 10:03 UTC
Everytime I open the SMAPI Stardew Valley it Crashes I need help

**Comment by KenaiHam** [comment] 2021-01-31 15:10
What version are you on?

**Comment by kingkane23** [comment] 2021-02-07 13:28
My version is 1.4

**Comment by UltimateShagiii** [comment] 2021-06-19 12:15
1.4.?.? What are the 2 numbers?

**Comment by ZaneYork** [comment] 2022-04-08 02:03
Duplicate of #175

**Closed by ZaneYork** 2022-04-08 02:03 UTC
