### ISSUE TITLE
Miui crash 3.7.6.9

### ISSUE THREAD

**Issue by 3D-House** [ZaneYork/SMAPI-Android-Installer#154] opened 2021-10-06 10:05 UTC
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zane.stardewvalley-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zane.stardewvalley-1/lib/arm64, /data/app/com.zane.stardewvalley-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libmonosgen-2.0.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:367)
	at java.lang.System.loadLibrary(System.java:1076)
	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:86)
	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:35)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5531)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5060)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5000)
	at android.app.ActivityThread.access$1800(ActivityThread.java:178)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5845)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

**Comment by ZaneYork** [comment] 2022-04-08 01:33
Duplicate of #170

**Closed by ZaneYork** 2022-04-08 01:33 UTC
