### ISSUE TITLE
Failed to sign game on newest version

### ISSUE THREAD

**Issue by snek-su** [ZaneYork/SMAPI-Android-Installer#131] opened 2021-04-07 11:33 UTC
![Screenshot_2021-04-07-19-18-55-527_com zane smapiinstaller](https://user-images.githubusercontent.com/82094696/113859683-c1326400-97d7-11eb-814e-423c929b3e25.jpg) Whenever I try to install SMAPI Stardew Valley on my phone, it gives an error that goes along the lines of "Failed to sign game, please contact developer"

My SDV version is 1.4.5.151

**Comment by Lalhmangaihsangi** [comment] 2021-05-24 06:45
Same im frustrated 😩

**Comment by emrednz07** [comment] 2021-07-22 15:47
Same version same problem

**Comment by Melo426** [comment] 2021-07-28 03:30
same here

**Comment by carmisantos** [comment] 2022-03-18 10:46
Pls help me how can we fix this problem

**Comment by ZaneYork** [comment] 2022-04-08 01:51
Duplicate of #178 
Looks like the sign logic was broken on some of device after 1.5.5

**Closed by ZaneYork** 2022-04-08 01:51 UTC

**Comment by yutta-329** [comment] 2023-09-14 02:22
I also have a problem every time I try to download smapi, my sdv version is 1.5.6.39
![Screenshot_2023-09-13-23-15-31-031_com zane smapiinstaller](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/144974904/21ebad91-7a7b-45b3-ada2-a9055213a7ea)
