### ISSUE TITLE
how to activate the music?

### ISSUE THREAD

**Issue by Edw13Edu13** [ZaneYork/SMAPI-Android-Installer#188] opened 2022-04-06 05:35 UTC
Every time I access smapi SV it asks for permission to access obb but it doesn't change anything, it's not working!

**Comment by ZaneYork** [comment] 2022-04-06 06:07
Please leave your OS vendor info and device info

**Comment by Edw13Edu13** [comment] 2022-04-07 00:51
the music just came back, I just restarted it and it worked perfectly, a thousand apologies for the inconvenience

**Comment by ZaneYork** [comment] 2022-04-07 09:23
Duplicate of #54

**Closed by ZaneYork** 2022-04-07 09:23 UTC
